apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shopnow.fullname" . }}-config
  labels:
    {{- include "shopnow.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  API_URL: {{ .Values.config.apiUrl | quote }}
  SUPPORT_EMAIL: {{ .Values.config.supportEmail | quote }}
